apiVersion: apps/v1
kind: Deployment
metadata:
  name: vammo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vammo
  template:
    metadata:
      labels:
        app: vammo
    spec:
      containers:
      - name: vammo
        image: 796796207873.dkr.ecr.ap-south-1.amazonaws.com/vammo-app:latest
        ports:
        - containerPort: 5000
